services:
  - type: web
    name: churn-prediction
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      cd src &&
      streamlit run app.py --server.port=$PORT --server.address=0.0.0.0