services:
  - type: web
    name: dashboard-wizard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run src/app.py --server.port=$PORT --server.address=0.0.0.0
    plan: free
