services:
  - type: web
    name: churn-prediction-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: MPLBACKEND
        value: Agg